version: '3'


services:
 
  website:
    image: php:apache
    depends_on: 
      - apiapp
    environment: 
      - USERNAME=toto
      - PASSWORD=python
    volumes: 
      - ./website:/var/www/html      
    ports:
      - "3000:80"
  
  apiapp:
    image: image
    volumes: 
      - /data 
    ports:
      - "5000:5000"

